server.port=8084

bot.name=family_chores_dev_bot
bot.token=${BOT_TOKEN}
#bot.uri=https://mytelegrambot.ru

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}