server.port=8084

bot.name=family_chores_bot
bot.token=${BOT_TOKEN}
bot.uri=https://geralyn-pseudosessile-jonas.ngrok-free.dev
#bot.uri=https://mytelegrambot.ru

server.ssl.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}