server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message
  datasource:
    url: jdbc:postgresql://localhost:5432/chores
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
      generate-ddl: true